inherit_from: .rubocop_todo.yml

Encoding:
  Enabled: false

Metrics/ClassLength:
  CountComments: false

Metrics/MethodLength:
  CountComments: false

AllCops:
  TargetRubyVersion: 2.3

  Exclude:
    - gqli.gemspec
    - spec/**/*
    - examples/**/*
    - Guardfile
    - Gemfile
    - Rakefile
    - usage*.rb

Metrics/ClassLength:
  Max: 250

Style/MutableConstant:
  Enabled: false

Style/SignalException:
  EnforcedStyle: 'semantic'

Style/DoubleNegation:
  Enabled: false
